# Generated by Django 5.1.2 on 2024-11-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.CharField(max_length=10)),
            ],
        ),
    ]
